export const CATEGORIES_FETCH = "CATEGORIES_FETCH";
export const CATEGORIES_FETCH_SUCCESS = "CATEGORIES_FETCH_SUCCESS";

export const POSTS_FETCH = "POSTS_FETCH";
export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS";
export const POSTS_CHANGE_SORT_BY = "POSTS_CHANGE_SORT_BY";

export const NEW_POST_CHANGE = "NEW_POST_CHANGE";
export const NEW_POST_SUBMITTED = "NEW_POST_SUBMITTED";
export const NEW_POST_SUBMITTED_SUCCESS = "NEW_POST_SUBMITTED_SUCCESS";
