export const CATEGORIES_FETCH = "CATEGORIES_FETCH";
export const CATEGORIES_FETCH_SUCCESS = "CATEGORIES_FETCH_SUCCESS";

export const POSTS_FETCH = "POSTS_FETCH";
export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS";
export const POSTS_CHANGE_SORT_BY = "POSTS_CHANGE_SORT_BY";

export const POST_FORM_CHANGE = "POST_FORM_CHANGE";
export const POST_FORM_SUBMITTED = "POST_FORM_SUBMITTED";
export const POST_FORM_SUBMITTED_SUCCESS = "POST_FORM_SUBMITTED_SUCCESS";
