export const CATEGORIES_FETCH = "CATEGORIES_FETCH";
export const CATEGORIES_FETCH_SUCCESS = "CATEGORIES_FETCH_SUCCESS";

export const POSTS_FETCH = "POSTS_FETCH";
export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS";
export const POSTS_CHANGE_SORT_BY = "POSTS_CHANGE_SORT_BY";

export const POST_FORM_CHANGE = "POST_FORM_CHANGE";
export const POST_FORM_SUBMITTED = "POST_FORM_SUBMITTED";
export const POST_FORM_POST_SUCCESS = "POST_FORM_POST_SUCCESS";
export const POST_FORM_PUT_SUCCESS = "POST_FORM_PUT_SUCCESS";
export const POST_FORM_SET_INITIAL_VALUES = "POST_FORM_SET_INITIAL_VALUES";
export const RESET_FORM = "RESET_FORM";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_UPVOTE_SUCCEEDED = "POST_UPVOTE_SUCCEEDED";

export const COMMENTS_FETCH_SUCCESS = "COMMENTS_FETCH_SUCCESS";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";

export const COMMENT_FORM_CHANGED = "COMMENT_FORM_CHANGED";
export const COMMENT_FORM_POST_SUCCESS = "COMMENT_FORM_POST_SUCCESS";
export const COMMENT_FORM_SET_INITIAL_VALUES =
  "COMMENT_FORM_SET_INITIAL_VALUES";
export const COMMENT_FORM_PUT_SUCCESS = "COMMENT_FORM_PUT_SUCCESS";
